GET http://localhost:3000/todos/1/
### API 5
DELETE http://localhost:3000/todos/1/
#### API 3
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

### API 1 
GET http://localhost:3000/todos/?status=TO%20DO

### API 4 
PUT http://localhost:3000/todos/1/?todo=fine
